[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "tennis muscle cattle potato climb ranch ramp nose inner wisdom dinner skate brush dilemma board tool exchange this sunny lawsuit soccer margin ritual soon"
